application:
  kafka:
    broker: "localhost:9092"
    serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    schema-registry-url: "http://localhost:8081"
    create-vote-request-topic: "create-vote-request"
    vote-created-event-topic: "vote-created-event"
server:
  port: 8090