version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/vma-gui"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
