version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      spring:
        patterns:
          - "*spring*"
      maven:
        patterns:
          - "*maven*"
      kotlin:
        patterns:
          - "*kotlin*"
      postgresql:
        patterns:
          - "postgresql*"
          - "*postgresql*"
          - "*postgresql"

  - package-ecosystem: "npm"
    directory: "/vma-gui"
    schedule:
      interval: "daily"
    groups:
      angular:
        patterns:
          - "@angular*"
          - "angular*"
          - "*angular*"
          - "@types*"
          - "*types*"

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
