version: "3.7"
services:
  jofisaes_vma_postgres_1:
    container_name: jofisaes_${PROJECT_NAME}_postgres_1
    hostname: jofisaes-vma-postgres-1
    restart: on-failure
    command: -c 'max_connections=400' -c 'shared_buffers=100MB'
    build:
      context: ./docker-images/psql/.
    volumes:
      - ./docker-images/psql/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - VMA_ETCD_IP=${VMA_ETCD_IP}
      - POSTGRES_MAIN_IP=${POSTGRES_1_IP}
      - POSTGRES_SECOND_IP=${POSTGRES_2_IP}
      - POSTGRES_THIRD_IP=${POSTGRES_3_IP}
      - POSTGRES_NUMBER=1
    expose:
      - ${PG_EXPOSED_PORT}
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 0s
    networks:
      vma_net:
        ipv4_address: ${POSTGRES_1_IP}

  jofisaes_vma_postgres_2:
    container_name: jofisaes_${PROJECT_NAME}_postgres_2
    hostname: jofisaes-vma-postgres-2
    restart: on-failure
    command: -c 'max_connections=400' -c 'shared_buffers=100MB'
    build:
      context: ./docker-images/psql/.
    volumes:
      - ./docker-images/psql/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - VMA_ETCD_IP=${VMA_ETCD_IP}
      - POSTGRES_MAIN_IP=${POSTGRES_2_IP}
      - POSTGRES_SECOND_IP=${POSTGRES_1_IP}
      - POSTGRES_THIRD_IP=${POSTGRES_3_IP}
      - POSTGRES_NUMBER=2
    expose:
      - ${PG_EXPOSED_PORT}
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 0s
    networks:
      vma_net:
        ipv4_address: ${POSTGRES_2_IP}

  jofisaes_vma_postgres_3:
    container_name: jofisaes_${PROJECT_NAME}_postgres_3
    hostname: jofisaes-vma-postgres-3
    restart: on-failure
    command: -c 'max_connections=400' -c 'shared_buffers=100MB'
    build:
      context: ./docker-images/psql/.
    volumes:
      - ./docker-images/psql/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - VMA_ETCD_IP=${VMA_ETCD_IP}
      - POSTGRES_MAIN_IP=${POSTGRES_3_IP}
      - POSTGRES_SECOND_IP=${POSTGRES_1_IP}
      - POSTGRES_THIRD_IP=${POSTGRES_2_IP}
      - POSTGRES_NUMBER=3
    expose:
      - ${PG_EXPOSED_PORT}
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 0s
    networks:
      vma_net:
        ipv4_address: ${POSTGRES_3_IP}

  jofisaes_vma_haproxy_lb:
    container_name: jofisaes_vma_haproxy_lb
    hostname: jofisaes_vma_haproxy_lb
    build: docker-images/haproxy/.
    expose:
      - 5001
      - 5000
      - 7000
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M
    networks:
      vma_net:
        ipv4_address: ${VMA_HA_PROXY_IP}
    depends_on:
      - jofisaes_vma_postgres_1
      - jofisaes_vma_postgres_2
      - jofisaes_vma_postgres_3
    environment:
      - POSTGRES_1_IP=${POSTGRES_1_IP}
      - POSTGRES_2_IP=${POSTGRES_2_IP}
      - POSTGRES_3_IP=${POSTGRES_3_IP}
      - POSTGRES_EXPOSED_PORT=${PG_EXPOSED_PORT}

  jofisaes_vma_backend_img_1:
    hostname: jofisaes_vma_backend_img_1
    container_name: jofisaes_vma_backend_img_1
    build:
      context: vma-service-backend/.
    expose:
      - 8081
    environment:
      - VMA_BACKEND_PROFILE=docker,starter
      - VMA_PORT=8081
      - VMA_HA_PROXY_IP=${VMA_HA_PROXY_IP}
      - VMA_SCHEMA_REGISTRY=${VMA_SCHEMA_REGISTRY}
      - VMA_KAFKA=${VMA_KAFKA}
    restart: on-failure
    depends_on:
      - jofisaes_vma_postgres_1
      - jofisaes_vma_postgres_2
      - jofisaes_vma_postgres_3
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 400M
    networks:
      vma_net:
        ipv4_address: ${VMA_BACKEND_1}

  jofisaes_vma_backend_img_2:
    hostname: jofisaes_vma_backend_img_2
    container_name: jofisaes_vma_backend_img_2
    build:
      context: vma-service-backend/.
    expose:
      - 8082
    environment:
      - VMA_BACKEND_PROFILE=docker
      - VMA_PORT=8082
      - VMA_HA_PROXY_IP=${VMA_HA_PROXY_IP}
      - VMA_SCHEMA_REGISTRY=${VMA_SCHEMA_REGISTRY}
      - VMA_KAFKA=${VMA_KAFKA}
    restart: on-failure
    depends_on:
      - jofisaes_vma_postgres_1
      - jofisaes_vma_postgres_2
      - jofisaes_vma_postgres_3
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 400M
    networks:
      vma_net:
        ipv4_address: ${VMA_BACKEND_2}

  jofisaes_vma_websockets_1:
    hostname: jofisaes_vma_websockets_1
    container_name: jofisaes_vma_websockets_1
    build:
      context: vma-service-websockets/.
    expose:
      - 8083
    environment:
      - VMA_BACKEND_PROFILE=docker,starter
      - VMA_PORT=8083
      - VMA_HA_PROXY_IP=${VMA_HA_PROXY_IP}
      - VMA_SCHEMA_REGISTRY=${VMA_SCHEMA_REGISTRY}
      - VMA_NGINX_IP=${VMA_NGINX_IP}

    restart: on-failure
    depends_on:
      - jofisaes_vma_postgres_1
      - jofisaes_vma_postgres_2
      - jofisaes_vma_postgres_3
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 400M
    networks:
      vma_net:
        ipv4_address: ${VMA_WEB_SOCKETS_1}

  jofisaes_vma_websockets_2:
    hostname: jofisaes_vma_websockets_2
    container_name: jofisaes_vma_websockets_2
    build:
      context: vma-service-websockets/.
    expose:
      - 8084
    environment:
      - VMA_BACKEND_PROFILE=docker,starter
      - VMA_PORT=8084
      - VMA_HA_PROXY_IP=${VMA_HA_PROXY_IP}
      - VMA_SCHEMA_REGISTRY=${VMA_SCHEMA_REGISTRY}
      - VMA_NGINX_IP=${VMA_NGINX_IP}
    restart: on-failure
    depends_on:
      - jofisaes_vma_postgres_1
      - jofisaes_vma_postgres_2
      - jofisaes_vma_postgres_3
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 400M
    networks:
      vma_net:
        ipv4_address: ${VMA_WEB_SOCKETS_2}

  jofisaes_vma_nginx_lb:
    hostname: jofisaes_vma_nginx_lb
    container_name: jofisaes_vma_nginx_lb
    build:
      context: ./docker-images/nginx/.
    expose:
      - 8080
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      vma_net:
        ipv4_address: ${VMA_NGINX_IP}

  jofisaes_vma_etcd:
    image: 'bitnami/etcd:latest'
    container_name: jofisaes_${PROJECT_NAME}_etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://${VMA_ETCD_IP}:2379
      - ETCD_ENABLE_V2=true
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 100M
    networks:
      vma_net:
        ipv4_address: ${VMA_ETCD_IP}

  jofisaes_vma_zookeeper:
    image: confluentinc/cp-zookeeper:5.4.0
    hostname: jofisaes_vma_zookeeper
    container_name: jofisaes_vma_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
    networks:
      vma_net:
        ipv4_address: ${VMA_ZOOKEEPER}

  jofisaes_vma_broker:
    image: confluentinc/cp-server:5.4.0
    hostname: jofisaes_vma_broker
    container_name: jofisaes_vma_broker
    depends_on:
      - jofisaes_vma_zookeeper
    expose:
      - 9092
      - 29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "${VMA_ZOOKEEPER}:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_PUBLIC:PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: LISTENER_PUBLIC://jofisaes_vma_broker:29092,LISTENER_INTERNAL://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_PUBLIC://jofisaes_vma_broker:29092,LISTENER_INTERNAL://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_PUBLIC
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: jofisaes_vma_broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: ${VMA_ZOOKEEPER}:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
      CONTROL_CENTER_SCHEMA_REGISTRY_SR1_URL: https://schemaregistry:8088
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 400M
    networks:
      vma_net:
        ipv4_address: ${VMA_KAFKA}

  jofisaes_schemaregistry:
    image: confluentinc/cp-schema-registry:5.4.0
    container_name: jofisaes_schemaregistry
    restart: always
    depends_on:
      - jofisaes_vma_broker
    volumes:
      - ./scripts/security:/etc/kafka/secrets
      - ./scripts/security/keypair:/tmp/conf
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8088
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: jofisaes_vma_broker:29092
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    networks:
      vma_net:
        ipv4_address: ${VMA_SCHEMA_REGISTRY}

  jofisaes_vma_listener_1:
    hostname: jofisaes_vma_listener_1
    container_name: jofisaes_vma_listener_1
    build:
      context: vma-service-event-listener/.
    environment:
      - VMA_PORT=9001
      - VMA_SCHEMA_REGISTRY=${VMA_SCHEMA_REGISTRY}
      - VMA_HA_PROXY_IP=${VMA_HA_PROXY_IP}
      - VMA_KAFKA=${VMA_KAFKA}
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    networks:
      vma_net:
        ipv4_address: ${VMA_LISTENER_1}

  jofisaes_vma_listener_2:
    hostname: jofisaes_vma_listener_2
    container_name: jofisaes_vma_listener_2
    build:
      context: vma-service-event-listener/.
    environment:
      - VMA_PORT=9002
      - VMA_SCHEMA_REGISTRY=${VMA_SCHEMA_REGISTRY}
      - VMA_HA_PROXY_IP=${VMA_HA_PROXY_IP}
      - VMA_KAFKA=${VMA_KAFKA}
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      vma_net:
        ipv4_address: ${VMA_LISTENER_2}

networks:
  vma_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
