version: "3.7"
services:
  jofisaes_vma_postgres_1:
    container_name: ${PROJECT_NAME}_postgres_1
    hostname: jofisaes-vma-postgres-1
    restart: on-failure
    build:
      context: ./docker-images/psql/.
    ports:
      - "5433:5432"
    env_file:
      - ./docker-images/psql/.env
    volumes:
      - ./docker-images/psql/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=vma
      - VMA_ETCD_IP=${VMA_ETCD_IP}
      - POSTGRES_MAIN_IP=${POSTGRES_1_IP}
      - POSTGRES_SECOND_IP=${POSTGRES_2_IP}
      - POSTGRES_NUMBER=2
    expose:
      - ${PG_EXPOSED_PORT}
    networks:
      vma_net:
        ipv4_address: ${POSTGRES_1_IP}


  jofisaes_vma_postgres_2:
    container_name: ${PROJECT_NAME}_postgres_2
    hostname: jofisaes-vma-postgres-2
    restart: on-failure
    build:
      context: ./docker-images/psql/.
    ports:
      - "5434:5432"
    env_file:
      - ./docker-images/psql/.env
    volumes:
      - ./docker-images/psql/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=vma
      - VMA_ETCD_IP=${VMA_ETCD_IP}
      - POSTGRES_MAIN_IP=${POSTGRES_2_IP}
      - POSTGRES_SECOND_IP=${POSTGRES_1_IP}
      - POSTGRES_NUMBER=1
    expose:
      - ${PG_EXPOSED_PORT}
    networks:
      vma_net:
        ipv4_address: ${POSTGRES_2_IP}

  jofisaes_vma_haproxy_lb:
    container_name: jofisaes_vma_haproxy_lb
    build: docker-images/haproxy/.
    ports:
      - "5000:5000"
      - "5001:5001"
      - "7000:7000"
    expose:
      - 5001
      - 5000
      - 7000
    networks:
      vma_net:
        ipv4_address: ${HA_PROXY_IP}
    environment:
      - POSTGRES_1_IP=${POSTGRES_1_IP}
      - POSTGRES_2_IP=${POSTGRES_2_IP}
      - POSTGRES_EXPOSED_PORT=${PG_EXPOSED_PORT}

  jofisaes_vma_backend_img_1:
    hostname: jofisaes_vma_backend_img_1
    container_name: jofisaes_vma_backend_img_1
    build:
      context: vma-service-backend/.
    ports:
      - "8081"
    environment:
      - VMA_PORT=8081
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      vma_net:
        ipv4_address: ${VMA_BACKEND_1}

  jofisaes_vma_backend_img_2:
    hostname: jofisaes_vma_backend_img_2
    container_name: jofisaes_vma_backend_img_2
    build:
      context: vma-service-backend/.
    ports:
      - "8082"
    environment:
      - VMA_PORT=8082
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      vma_net:
        ipv4_address: ${VMA_BACKEND_2}

  jofisaes_vma_backend_img_3:
    hostname: jofisaes_vma_backend_img_3
    container_name: jofisaes_vma_backend_img_3
    build:
      context: vma-service-backend/.
    ports:
      - "8083"
    environment:
      - VMA_PORT=8083
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
    networks:
      vma_net:
        ipv4_address: ${VMA_BACKEND_3}

  jofisaes_vma_nginx_lb:
    hostname: jofisaes_vma_nginx_lb
    container_name: jofisaes_vma_nginx_lb
    build:
      context: ./docker-images/nginx/.
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    env_file:
      - .env
    networks:
      vma_net:
        ipv4_address: ${VMA_NGINX_IP}

  jofisaes_vma_etcd:
    image: 'bitnami/etcd:latest'
    container_name: jofisaes_${PROJECT_NAME}_etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://${VMA_ETCD_IP}:2379
      - ETCD_ENABLE_V2=true
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: on-failure
    networks:
      vma_net:
        ipv4_address: ${VMA_ETCD_IP}

networks:
  vma_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
