# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: Install SDK 25
          command: wget https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25%2B36/OpenJDK25U-jdk_x64_linux_hotspot_25_36.tar.gz &&
            tar -xvf OpenJDK25U-jdk_x64_linux_hotspot_25_36.tar.gz &&
            sudo mv jdk-25*/ /opt/jdk25 &&
            export JAVA_HOME=/opt/jdk25 &&
            export PATH=$PATH:$JAVA_HOME/bin

      - run:
          name: Build
          command: export JAVA_HOME=/opt/jdk25 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn -B -DskipTests clean package

      - run:
          name: Test
          command: export JAVA_HOME=/opt/jdk25 &&
              export PATH=$PATH:$JAVA_HOME/bin &&
              mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

