version: 2.1
orbs:
  maven: circleci/maven@1.4.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:25.0
    steps:
      - checkout
      - maven/install:
          command: '-B -DskipTests clean package'
      - maven/test:
          command: 'test'
workflows:
  maven_workflow:
    jobs:
      - build

