scope: postgres
namespace: /db/
name: postgresql${POSTGRES_NUMBER}

restapi:
  listen: ${POSTGRES_MAIN_IP}:8008
  connect_address: ${POSTGRES_MAIN_IP}:8008

etcd:
  hosts: ${VMA_ETCD_IP}:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - host replication postgres 127.0.0.1/32 md5
    - host replication postgres ${POSTGRES_MAIN_IP}/0 md5
    - host replication postgres ${POSTGRES_SECOND_IP}/0 md5
    - host replication postgres ${POSTGRES_THIRD_IP}/0 md5
    - host all all 0.0.0.0/0 md5

  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb

postgresql:
  listen: 0.0.0.0:5432
  connect_address: ${POSTGRES_MAIN_IP}:5432
  data_dir: /data/patroni
  bin_dir: /usr/lib/postgresql/11/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: postgres
      password: admin
    superuser:
      username: postgres
      password: admin
  parameters:
    unix_socket_directories: '.'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
