cypress-open:
	yarn && npm run cypress
cypress-electron:
	docker-compose up e2e-electron
cypress-chrome:
	docker-compose up e2e-chrome
cypress-firefox:
	docker-compose up e2e-firefox
cypress-edge:
	docker-compose up e2e-edge
