category:
	curl -X POST -H "Content-Type: application/json" --data "@category.json" http://localhost:8080/api/vma/registry
songs:
	curl -X POST -H "Content-Type: application/json" --data "@songs.json" http://localhost:8080/api/vma/registry/random