post-category:
	curl -X POST -H "Content-Type: application/json" --data "@category.json" http://localhost:8080/api/vma/registry
post-songs:
	curl -X POST -H "Content-Type: application/json" --data "@songs.json" http://localhost:8080/api/vma/registry/random
get-songs:
	curl -i  http://localhost:8080/api/vma/registry/current
