# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: vma-archiver

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew clean test build
    - name: Coverage with Gradle
      run: ./gradlew build jacocoTestReport coveralls
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
      env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Codacy Coverage
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java $(find **/jacoco*.xml -printf '-r %p ')
      env:
         CODECOV_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
