name: E2E e2e-vma-archiver-app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Locust
        run: make install

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action

      - name: Start Locust
        run: make locust
      - name: Run Cypress
        run: make cypress-electron

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Locust
        run: make install

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action

      - name: Start Locust
        run: make locust-short
      - name: Run Cypress
        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Locust
        run: make install

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action

      - name: Start Locust
        run: make locust-short
      - name: Run Cypress
        run: make cypress-firefox


  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Locust
        run: make install

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action

      - name: Start Locust
        run: make locust-short
      - name: Run Cypress
        run: make cypress-edge

