name: E2E e2e-vma-archiver-app

on:
  pull_request:
    branches: [ master ]

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Locust
        run: make install

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action
      - name: Docker Startup Fail!
        if: failure()
        run: |
          make docker-logs
      - name: Start Locust
        run: make locust
      - name: Run Cypress
        run: make cypress-electron

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Locust
        run: make install

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action
      - name: Docker Startup Fail!
        if: failure()
        run: |
          make docker-logs
      - name: Start Locust
        run: make locust-short
      - name: Run Cypress
        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Locust
        run: make install

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action
      - name: Docker Startup Fail!
        if: failure()
        run: |
          make docker-logs
      - name: Start Locust
        run: make locust-short
      - name: Run Cypress
        run: make cypress-firefox


  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Locust
        run: make install
      - name: Docker Startup Fail!
        if: failure()
        run: |
          make docker-logs
      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 5
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action

      - name: Start Locust
        run: make locust-short
      - name: Run Cypress
        run: make cypress-edge

